[system]
packages = [
    "libnss3",
    "libatk1.0-0",
    "libatk-bridge2.0-0",
    "libx11-xcb1",
    "libxcomposite1",
    "libxrandr2",
    "libxdamage1",
    "libxext6",
    "libxfixes3",
    "libpangocairo-1.0-0",
    "libpango-1.0-0",
    "libgtk-3-0",
    "libgdk-pixbuf2.0-0",
    "libdbus-1-3",
    "libasound2",
    "fonts-liberation"
]
