[system]
packages = [
    "libnss3",
    "libx11",
    "libxcomposite",
    "libxdamage",
    "libxrandr",
    "libasound2",
    "libatk1.0",
    "libcairo2",
    "libcups2",
    "libdbus-1-3",
    "libgdk-pixbuf2.0-0",
    "libgtk-3-0",
    "libpango-1.0-0",
    "libxshmfence",
    "fonts-liberation"
]
